- name: Ensure .zshrc exists
  file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: touch
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Create alias for dotfiles
  lineinfile:
    path: "{{ansible_user_dir}}/.zshrc"
    line: alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
    create: yes
- name: Backup conf files
  shell: mkdir -p ~/.dotfiles-backup && git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME checkout 2>&1 | egrep "\s+\." | awk {'print $2'} | xargs -I{} mkdir -p $HOME/.dotfiles-backup/{} && cp -p $HOME/{} $HOME/.dotfiles-backup/{}

- name: Clone dotfiles
  # I set force and update to "no" so that if I have any working changes or changes that I haven't pushed up it doesn't reset my local history.
  git:
    repo: https://github.com/4volodin/dotfiles.git
    dest: "{{ansible_user_dir}}/.dotfiles.git"
    bare: true
    clone: true
    force: false
    update: false

- name: Checkout dotfiles
  shell: |
    git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME config --local status.showUntrackedFiles no
    git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME checkout
