---
# Time Machine starts at 7:35 and repeat in 12 hours
- name: Start services at login
  copy:
    src: timemachine/com.voale.tmutil-backup.plist
    dest: ~/Library/LaunchAgents/com.voale.tmutil-backup.plist

- name: Setup launch agents for services
  shell: launchctl load -w ~/Library/LaunchAgents/com.voale.tmutil-backup.plist

# ---------------------------------------------------------
# Symlink to icloud
- name: Start services at login
  file: src="~/Library/Mobile\ Documents/com\~apple\~CloudDocs" dest="~/icloud" state=link force=yes

#
# ---------------------------------------------------------
# iPhone backup location
#- name: Start services at login
#  file: src=~/Library/Application\ Support/MobileSync/Backup/ path=/Volumes/voale-raid1-400Gb/ios_backup state=link force=yes

# ---------------------------------------------------------
#
- name: Loopback interface
  tags: loopback
  copy:
    src: loopback-alias/com.user.lo0-loopback.plist
    dest: /Library/LaunchDaemons/com.user.lo0-loopback.plist
    owner: root
    group: wheel
    mode: "0644"
  become: true
- name: Setup launch agent for loopback alias
  tags: loopback
  shell: launchctl load -w /Library/LaunchDaemons/com.user.lo0-loopback.plist
  become: true

# ---------------------------------------------------------
# Enable Dark mode notify
# or use launchctl load -F ...
- name: Enable Dark mode notify
  copy:
    src: dark-mode-notify/com.voale.dark-mode-notify.plist
    dest: ~/Library/LaunchAgents/com.voale.dark-mode-notify.plist
- name: Lauch dark mode notify
  shell: launchctl load -w ~/Library/LaunchAgents/com.voale.dark-mode-notify.plist
# ---------------------------------------------------------
#
- name: Disable microphone
  copy:
    src: microphone/com.voale.mic-disable.plist
    dest: ~/Library/LaunchAgents/com.voale.mic-disable.plist
- name: Launch
  shell: launchctl load -w ~/Library/LaunchAgents/com.voale.mic-disable.plist

# ---------------------------------------------------------
#
# ---------------------------------------------------------
- name: Toggle microphone
  copy:
    src: mic-toggle/Mic-OnOff.workflow
    dest: ~/Library/Services

# ---------------------------------------------------------
#
- name: Reset quick look
  shell: |
    sudo xattr -cr ~/Library/QuickLook/*.qlgenerator
    qlmanage -r
    qlmanage -r cache

# ---------------------------------------------------------
- name: Delete Adoobe plist
  file:
    path: /Library/{{ item }}
    state: absent
  with_items:
    - LaunchDaemons/com.adobe.acc.installer.v2.plist
    - LaunchDaemons/com.adobe.agsservice.plist
    - LaunchAgents/com.adobe.AdobeCreativeCloud.plist
    - LaunchAgents/com.adobe.ccxprocess.plist
  become: true

# ---------------------------------------------------------
# find files in ~/Downloads which haven’t been modified within the past 2 weeks and move them into ~/.Trash.
# find ~/Downloads -type f -mtime +14 -exec mv {} ~/.Trash/ \\;
# mv ~/Downloads/*(mw+2) ~/.Trash
# Go to System Settings app (Control Panel for older macOS)->Privacy & Security->Full Disk Access. You will see a panel with programs listed
# The only way to get /bin/sh into that list is bring up a Finder window and pick the Go To Folder menu and type /bin/sh then drag the sh file into the list.
# Make sure the sh entry has the switch on for enabling access
- name: Clean Downloads
  tags: cleandownloads
  copy:
    src: cleandownloads/com.voale.cleandownloads.plist
    dest: ~/Library/LaunchAgents/com.voale.cleandownloads.plist
- name: Launch cleandownloads
  tags: cleandownloads
  shell: launchctl load -w ~/Library/LaunchAgents/com.voale.cleandownloads.plist

# ---------------------------------------------------------
# find ~/Desktop/Screenshots/ -type f -mtime +7 -exec rm -f {} \\;
- name: Remove screenshots older than 7 days from Desktop
  tags: cleanscreenshots
  copy:
    src: cleanscreenshots/com.voale.cleanscreenshots.plist
    dest: ~/Library/LaunchAgents/com.voale.cleanscreenshots.plist
- name: Launch cleanscreenshots
  tags: cleanscreenshots
  shell: launchctl load -w ~/Library/LaunchAgents/com.voale.cleanscreenshots.plist


# ---------------------------------------------------------
#
- name: Create ~/Library/LaunchAgents
  file:
    path: ~/.local/share/nvim/backup
    state: directory
    mode: "0755"

